course_name = "模拟电子技术基础"
course_code = "EE1007"

notices = """
注意，模拟电子技术实验（[EE1008](https://hoa.moe/docs/sophomore-spring/ee1008/)）是独立设课。
"""

[[lecturers]]
name = "毕淑娥"
  [[lecturers.reviews]]
  content = """
每节课都会点同学回答问题（相当于考勤）
念 PPT，比较无聊
布置作业均来自教材课后习题
"""
  author = { name = "", link = "", date = "" }

[[lecturers]]
name = "谷雨"
  [[lecturers.reviews]]
  content = """
会有随堂小测，现场做题
会用幻灯片，适当结合板书，对于题目的做法讲解细致。
能把魔法电路的魔法原理清楚明白地让绝大多数同学能听懂，定性定量结合，风格类似上交大郑益慧。
而且老师上课活力十足，绝对不会无聊
"""
  author = { name = "", link = "", date = "" }

[[textbooks]]
title = "模拟电子技术基础"
book_author = "清华大学童诗白、华成英主编"
publisher = "高等教育出版社"
edition = "第五版或第六版"
type = "textbook"
author = { name = "", link = "", date = "" }

[[textbooks]]
title = "新概念模拟电路"
book_author = "西安交通大学杨建国"
publisher = ""
edition = ""
type = "reference"
author = { name = "", link = "", date = "" }

[[textbooks]]
title = "The Art of Electronics"
book_author = "Paul Horowitz & Winfield Hill"
publisher = ""
edition = "3rd ed."
type = "reference"
author = { name = "", link = "", date = "" }

[[textbooks]]
title = "模拟电子技术基础学习辅导与习题解答"
book_author = "清华大学华成英主编"
publisher = "高等教育出版社"
edition = ""
type = "reference"
author = { name = "", link = "", date = "" }

[[textbooks]]
title = "模拟电子技术"
book_author = "Robert L. Boylestad等著，李立华等译"
publisher = "电子工业出版社"
edition = "第九版"
type = "reference"
author = { name = "", link = "", date = "" }

[[online_resources]]
title = "模拟电子技术基础 上交大 郑益慧主讲"
url = "https://www.bilibili.com/video/BV1Gt411b7Zq"
description = ""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2023-12-01" }

[[online_resources]]
title = "华成英 - 模拟电子技术基础"
url = "https://www.bilibili.com/video/BV19s411a7KL"
description = ""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2023-12-01" }

[[online_resources]]
title = "模拟电子技术基础第1-9章习题讲解"
url = "https://www.bilibili.com/video/BV1i14y1b7TM/"
description = """
对于作业，尽量不要只抄指导书的答案而不加以思考。指导书的解题过程较为呆板，如果无法理解，可以参考以下习题讲解视频，两个视频风格不同，可以相互补充：
第一个视频更加从定量计算的角度去解决问题，遇到题目会更加愿意去画出其直流通路、交流通路（如果需要，分别画出低频段、中频段、高频段等效电路）通过计算解决问题，从而打牢基础
第二个视频更从定性分析的角度去解决问题，会更多地应用在前面学习的过程中积累的性质和思路去解决后面的问题，更能培养做题的直觉
"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-07-01" }

[[online_resources]]
title = "童诗白&华成英 教材 第五版 课后习题讲解"
url = "https://www.bilibili.com/video/BV1mB4y1v79T/"
description = ""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-07-01" }

course = []

[[exam]]
content = """
考试难度每年有所波动，但是相比于模拟电子技术课程本身的深度和抽象程度来说，一般都算是容易的，没有太多变来变去的东西，重在考查基本概念。
如果需要锻炼设计和搭建电路的经验，可以在学习数字电子技术后报名电子设计大赛。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2023-12-01" }

[[exam]]
content = """
24 年春自动化模电考试难度较大，既考察了很细节的知识点（比如 PN 结的扩散运动和漂移运动）又考察了题目理解和绘图能力（画二阶阻容耦合共射放大电路的全频段等效电路），还考察了「卓尔不凡的视力」和读题的细致程度……总之是一次很综合很有挑战性的考试，需要将两个小时的考试时间都用满。
不可轻信「往届惯例」，24 年和 23 年的模电考试难度差别很大
围绕考前老师发的复习提纲（包括各个知识点所需要的掌握程度、对应的例题和作业题）展开复习，这可以看做是考纲，若有不清楚的地方可以尽早询问老师，做好复习规划
"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-07-01" }

lab = []

advice = []

schedule = []

related_links = []

[[misc]]
content = "以下资料中的《模电笔记1》来自“自动化学习交流群”，但我们未能与原作者取得联系。如果您是这份笔记的作者，请联系我们，我们将会标注你的名字和版权信息，谢谢！"
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-07-01" }