course_name = "模拟电子技术基础"
repo_type = "normal"
course_code = "EE1007"

description = "注意，模拟电子技术实验（EE1008）是独立设课。"

[[lecturers]]
name = "毕淑娥"

[[lecturers.reviews]]
content = """
每节课都会点同学回答问题（相当于考勤）。
念 PPT，比较无聊。
布置作业均来自教材课后习题。
"""

[[lecturers]]
name = "谷雨"

[[lecturers.reviews]]
content = """
会有随堂小测，现场做题。
会用幻灯片，适当结合板书，对于题目的做法讲解细致。
能把魔法电路的魔法原理清楚明白地让绝大多数同学能听懂，定性定量结合，风格类似上交大郑益慧。
而且老师上课活力十足，绝对不会无聊。
"""


[[sections]]
title = "教材"

[[sections.items]]
content = """
- **模拟电子技术基础**（童诗白 / 华成英 / 高等教育出版社 / 第五版或第六版 / textbook）
- **新概念模拟电路**（杨建国 / 西安交通大学 / textbook）
- **The Art of Electronics**（Paul Horowitz & Winfield Hill / 3rd ed. / textbook）
- **模拟电子技术基础学习辅导与习题解答**（华成英 / 高等教育出版社 / textbook）
- **模拟电子技术**（Robert L. Boylestad 著 / 李立华 等译 / 电子工业出版社 / 第九版 / textbook）
"""


[[sections]]
title = "在线资源"

[[sections.items]]
content = """
- [模拟电子技术基础 上交大 郑益慧主讲](https://www.bilibili.com/video/BV1Gt411b7Zq)：B站网课
- [华成英 - 模拟电子技术基础](https://www.bilibili.com/video/BV19s411a7KL)：B站网课
- [模拟电子技术基础第1-9章习题讲解](https://www.bilibili.com/video/BV1i14y1b7TM/)：从定量计算的角度解决问题，画直流通路、交流通路，打牢基础。
- [童诗白&华成英 教材 第五版 课后习题讲解](https://www.bilibili.com/video/BV1mB4y1v79T/)：从定性分析的角度解决问题，利用积累的性质和思路，培养做题直觉。
"""


[[sections]]
title = "关于考试"

[[sections.items]]
content = """
考试难度每年有所波动，但是相比于模拟电子技术课程本身的深度和抽象程度来说，一般都算是容易的，没有太多变来变去的东西，重在考查基本概念。
如果需要锻炼设计和搭建电路的经验，可以在学习数字电子技术后报名电子设计大赛。
"""

[[sections.items]]
content = """
24 年春自动化模电考试难度较大，既考察了很细节的知识点（比如 PN 结的扩散运动和漂移运动）又考察了题目理解和绘图能力（画二阶阻容耦合共射放大电路的全频段等效电路），还考察了「卓尔不凡的视力」和读题的细致程度……总之是一次很综合很有挑战性的考试，需要将两个小时的考试时间都用满。
不可轻信「往届惯例」，24 年和 23 年的模电考试难度差别很大。
建议围绕考前老师发的复习提纲（包括各个知识点所需要的掌握程度、对应的例题和作业题）展开复习，这可以看做是考纲，若有不清楚的地方可以尽早询问老师，做好复习规划。
"""


[[sections]]
title = "学习建议"

[[sections.items]]
content = "对于作业，尽量不要只抄指导书的答案而不加以思考。指导书的解题过程较为呆板，如果无法理解，可以参考相关习题讲解视频。"


[[sections]]
title = "资料来源说明"

[[sections.items]]
content = "资料中的《模电笔记1》来自“自动化学习交流群”，但我们未能与原作者取得联系。如果您是这份笔记的作者，请联系我们，我们将会标注你的名字和版权信息，谢谢！"
